# Generated by Django 2.0.1 on 2023-10-05 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsapp', '0002_contact_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='date_expired',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
